// <auto-generated />
using System;
using System.Collections.Generic;
using Langoose.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Langoose.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260412150555_InitialFoundation")]
    partial class InitialFoundation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DictionaryEntryDictionaryEntry", b =>
                {
                    b.Property<Guid>("DictionaryEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("dictionary_entry_id");

                    b.Property<Guid>("TranslationsId")
                        .HasColumnType("uuid")
                        .HasColumnName("translations_id");

                    b.HasKey("DictionaryEntryId", "TranslationsId")
                        .HasName("pk_dictionary_entry_dictionary_entry");

                    b.HasIndex("TranslationsId")
                        .HasDatabaseName("ix_dictionary_entry_dictionary_entry_translations_id");

                    b.ToTable("dictionary_entry_dictionary_entry", (string)null);
                });

            modelBuilder.Entity("EntryContextEntryContext", b =>
                {
                    b.Property<Guid>("EntryContextId")
                        .HasColumnType("uuid")
                        .HasColumnName("entry_context_id");

                    b.Property<Guid>("TranslationsId")
                        .HasColumnType("uuid")
                        .HasColumnName("translations_id");

                    b.HasKey("EntryContextId", "TranslationsId")
                        .HasName("pk_entry_context_entry_context");

                    b.HasIndex("TranslationsId")
                        .HasDatabaseName("ix_entry_context_entry_context_translations_id");

                    b.ToTable("entry_context_entry_context", (string)null);
                });

            modelBuilder.Entity("Langoose.Domain.Models.ContentFlag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("DictionaryEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("dictionary_entry_id");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("boolean")
                        .HasColumnName("is_resolved");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<Guid?>("ReportedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("reported_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_content_flags");

                    b.HasIndex("DictionaryEntryId")
                        .HasDatabaseName("ix_content_flags_dictionary_entry_id");

                    b.ToTable("content_flags", (string)null);
                });

            modelBuilder.Entity("Langoose.Domain.Models.DictionaryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BaseEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("base_entry_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Difficulty")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("difficulty");

                    b.Property<string>("GrammarLabel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("grammar_label");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("language");

                    b.Property<string>("PartOfSpeech")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("part_of_speech");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("text");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_dictionary_entries");

                    b.HasIndex("BaseEntryId")
                        .HasDatabaseName("ix_dictionary_entries_base_entry_id");

                    b.HasIndex("Language", "Text")
                        .HasDatabaseName("ix_dictionary_entries_language_text");

                    b.ToTable("dictionary_entries", (string)null);
                });

            modelBuilder.Entity("Langoose.Domain.Models.EntryContext", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cloze")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cloze");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("DictionaryEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("dictionary_entry_id");

                    b.Property<string>("Difficulty")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("difficulty");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_entry_contexts");

                    b.HasIndex("DictionaryEntryId")
                        .HasDatabaseName("ix_entry_contexts_dictionary_entry_id");

                    b.ToTable("entry_contexts", (string)null);
                });

            modelBuilder.Entity("Langoose.Domain.Models.ImportRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("PendingCount")
                        .HasColumnType("integer")
                        .HasColumnName("pending_count");

                    b.Property<int>("RowCount")
                        .HasColumnType("integer")
                        .HasColumnName("row_count");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_import_records");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_import_records_user_id");

                    b.ToTable("import_records", (string)null);
                });

            modelBuilder.Entity("Langoose.Domain.Models.StudyEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("DictionaryEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("dictionary_entry_id");

                    b.Property<Guid?>("EntryContextId")
                        .HasColumnType("uuid")
                        .HasColumnName("entry_context_id");

                    b.Property<string>("FeedbackCode")
                        .HasColumnType("text")
                        .HasColumnName("feedback_code");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("UserInput")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_input");

                    b.Property<string>("Verdict")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("verdict");

                    b.HasKey("Id")
                        .HasName("pk_study_events");

                    b.HasIndex("DictionaryEntryId")
                        .HasDatabaseName("ix_study_events_dictionary_entry_id");

                    b.HasIndex("EntryContextId")
                        .HasDatabaseName("ix_study_events_entry_context_id");

                    b.HasIndex("UserId", "CreatedAtUtc")
                        .HasDatabaseName("ix_study_events_user_id_created_at_utc");

                    b.ToTable("study_events", (string)null);
                });

            modelBuilder.Entity("Langoose.Domain.Models.UserDictionaryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("DictionaryEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("dictionary_entry_id");

                    b.Property<int>("EnrichmentAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("enrichment_attempts");

                    b.Property<DateTimeOffset?>("EnrichmentNotBefore")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enrichment_not_before");

                    b.Property<string>("EnrichmentStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("enrichment_status");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("SourceLanguage")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("source_language");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<string>("TargetLanguage")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("target_language");

                    b.Property<string>("Type")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("UserInputTerm")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("user_input_term");

                    b.Property<string>("UserInputTranslation")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("user_input_translation");

                    b.HasKey("Id")
                        .HasName("pk_user_dictionary_entries");

                    b.HasIndex("DictionaryEntryId")
                        .HasDatabaseName("ix_user_dictionary_entries_dictionary_entry_id");

                    b.HasIndex("EnrichmentStatus", "CreatedAtUtc")
                        .HasDatabaseName("ix_user_dictionary_entries_enrichment_status_created_at_utc");

                    b.HasIndex("UserId", "DictionaryEntryId")
                        .HasDatabaseName("ix_user_dictionary_entries_user_id_dictionary_entry_id");

                    b.ToTable("user_dictionary_entries", (string)null);
                });

            modelBuilder.Entity("Langoose.Domain.Models.UserProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("DictionaryEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("dictionary_entry_id");

                    b.Property<double?>("Difficulty")
                        .HasColumnType("double precision")
                        .HasColumnName("difficulty");

                    b.Property<DateTimeOffset>("DueAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_at_utc");

                    b.Property<int>("FailureCount")
                        .HasColumnType("integer")
                        .HasColumnName("failure_count");

                    b.Property<DateTimeOffset?>("LastReviewedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_reviewed_at_utc");

                    b.Property<double?>("Stability")
                        .HasColumnType("double precision")
                        .HasColumnName("stability");

                    b.Property<int>("SuccessCount")
                        .HasColumnType("integer")
                        .HasColumnName("success_count");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_progress");

                    b.HasIndex("DictionaryEntryId")
                        .HasDatabaseName("ix_user_progress_dictionary_entry_id");

                    b.HasIndex("UserId", "DictionaryEntryId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_progress_user_id_dictionary_entry_id");

                    b.HasIndex("UserId", "DueAtUtc")
                        .HasDatabaseName("ix_user_progress_user_id_due_at_utc");

                    b.ToTable("user_progress", (string)null);
                });

            modelBuilder.Entity("DictionaryEntryDictionaryEntry", b =>
                {
                    b.HasOne("Langoose.Domain.Models.DictionaryEntry", null)
                        .WithMany()
                        .HasForeignKey("DictionaryEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dictionary_entry_dictionary_entry_dictionary_entries_dictio");

                    b.HasOne("Langoose.Domain.Models.DictionaryEntry", null)
                        .WithMany()
                        .HasForeignKey("TranslationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dictionary_entry_dictionary_entry_dictionary_entries_transl");
                });

            modelBuilder.Entity("EntryContextEntryContext", b =>
                {
                    b.HasOne("Langoose.Domain.Models.EntryContext", null)
                        .WithMany()
                        .HasForeignKey("EntryContextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_entry_context_entry_context_entry_contexts_entry_context_id");

                    b.HasOne("Langoose.Domain.Models.EntryContext", null)
                        .WithMany()
                        .HasForeignKey("TranslationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_entry_context_entry_context_entry_contexts_translations_id");
                });

            modelBuilder.Entity("Langoose.Domain.Models.ContentFlag", b =>
                {
                    b.HasOne("Langoose.Domain.Models.DictionaryEntry", "DictionaryEntry")
                        .WithMany()
                        .HasForeignKey("DictionaryEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_content_flags_dictionary_entries_dictionary_entry_id");

                    b.Navigation("DictionaryEntry");
                });

            modelBuilder.Entity("Langoose.Domain.Models.DictionaryEntry", b =>
                {
                    b.HasOne("Langoose.Domain.Models.DictionaryEntry", "BaseEntry")
                        .WithMany("DerivedForms")
                        .HasForeignKey("BaseEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_dictionary_entries_dictionary_entries_base_entry_id");

                    b.Navigation("BaseEntry");
                });

            modelBuilder.Entity("Langoose.Domain.Models.EntryContext", b =>
                {
                    b.HasOne("Langoose.Domain.Models.DictionaryEntry", "DictionaryEntry")
                        .WithMany("Contexts")
                        .HasForeignKey("DictionaryEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_entry_contexts_dictionary_entries_dictionary_entry_id");

                    b.Navigation("DictionaryEntry");
                });

            modelBuilder.Entity("Langoose.Domain.Models.StudyEvent", b =>
                {
                    b.HasOne("Langoose.Domain.Models.DictionaryEntry", "DictionaryEntry")
                        .WithMany()
                        .HasForeignKey("DictionaryEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_study_events_dictionary_entries_dictionary_entry_id");

                    b.HasOne("Langoose.Domain.Models.EntryContext", "EntryContext")
                        .WithMany()
                        .HasForeignKey("EntryContextId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_study_events_entry_contexts_entry_context_id");

                    b.Navigation("DictionaryEntry");

                    b.Navigation("EntryContext");
                });

            modelBuilder.Entity("Langoose.Domain.Models.UserDictionaryEntry", b =>
                {
                    b.HasOne("Langoose.Domain.Models.DictionaryEntry", "DictionaryEntry")
                        .WithMany()
                        .HasForeignKey("DictionaryEntryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_user_dictionary_entries_dictionary_entries_dictionary_entry");

                    b.Navigation("DictionaryEntry");
                });

            modelBuilder.Entity("Langoose.Domain.Models.UserProgress", b =>
                {
                    b.HasOne("Langoose.Domain.Models.DictionaryEntry", "DictionaryEntry")
                        .WithMany()
                        .HasForeignKey("DictionaryEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_progress_dictionary_entries_dictionary_entry_id");

                    b.Navigation("DictionaryEntry");
                });

            modelBuilder.Entity("Langoose.Domain.Models.DictionaryEntry", b =>
                {
                    b.Navigation("Contexts");

                    b.Navigation("DerivedForms");
                });
#pragma warning restore 612, 618
        }
    }
}
