// <auto-generated />
using System;
using System.Collections.Generic;
using Langoose.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Langoose.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260411173324_InitialNewDomainModel")]
    partial class InitialNewDomainModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Langoose.Domain.Models.ContentFlag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DictionaryEntryId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("boolean");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ReportedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DictionaryEntryId");

                    b.ToTable("content_flags", (string)null);
                });

            modelBuilder.Entity("Langoose.Domain.Models.ContextTranslation", b =>
                {
                    b.Property<Guid>("SourceContextId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetContextId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SourceContextId", "TargetContextId");

                    b.HasIndex("TargetContextId");

                    b.ToTable("context_translations", (string)null);
                });

            modelBuilder.Entity("Langoose.Domain.Models.DictionaryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BaseEntryId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Difficulty")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("GrammarLabel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsBaseForm")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BaseEntryId");

                    b.HasIndex("Language", "Text");

                    b.ToTable("dictionary_entries", (string)null);
                });

            modelBuilder.Entity("Langoose.Domain.Models.EntryContext", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cloze")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DictionaryEntryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Difficulty")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DictionaryEntryId");

                    b.ToTable("entry_contexts", (string)null);
                });

            modelBuilder.Entity("Langoose.Domain.Models.EntryTranslation", b =>
                {
                    b.Property<Guid>("SourceEntryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetEntryId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SourceEntryId", "TargetEntryId");

                    b.HasIndex("TargetEntryId");

                    b.ToTable("entry_translations", (string)null);
                });

            modelBuilder.Entity("Langoose.Domain.Models.ImportRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("PendingCount")
                        .HasColumnType("integer");

                    b.Property<int>("RowCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("import_records", (string)null);
                });

            modelBuilder.Entity("Langoose.Domain.Models.StudyEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DictionaryEntryId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EntryContextId")
                        .HasColumnType("uuid");

                    b.Property<string>("FeedbackCode")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserInput")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Verdict")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DictionaryEntryId");

                    b.HasIndex("EntryContextId");

                    b.HasIndex("UserId");

                    b.ToTable("study_events", (string)null);
                });

            modelBuilder.Entity("Langoose.Domain.Models.UserDictionaryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DictionaryEntryId")
                        .HasColumnType("uuid");

                    b.Property<int>("EnrichmentAttempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("EnrichmentNotBefore")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EnrichmentStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("SourceLanguage")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("TargetLanguage")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Type")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserInputTerm")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("UserInputTranslation")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("DictionaryEntryId");

                    b.HasIndex("EnrichmentStatus");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "DictionaryEntryId");

                    b.ToTable("user_dictionary_entries", (string)null);
                });

            modelBuilder.Entity("Langoose.Domain.Models.UserProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DictionaryEntryId")
                        .HasColumnType("uuid");

                    b.Property<double?>("Difficulty")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("DueAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FailureCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LastReviewedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("Stability")
                        .HasColumnType("double precision");

                    b.Property<int>("SuccessCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DictionaryEntryId");

                    b.HasIndex("UserId", "DictionaryEntryId")
                        .IsUnique();

                    b.HasIndex("UserId", "DueAtUtc");

                    b.ToTable("user_progress", (string)null);
                });

            modelBuilder.Entity("Langoose.Domain.Models.ContentFlag", b =>
                {
                    b.HasOne("Langoose.Domain.Models.DictionaryEntry", "DictionaryEntry")
                        .WithMany()
                        .HasForeignKey("DictionaryEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DictionaryEntry");
                });

            modelBuilder.Entity("Langoose.Domain.Models.ContextTranslation", b =>
                {
                    b.HasOne("Langoose.Domain.Models.EntryContext", "SourceContext")
                        .WithMany("SourceContextTranslations")
                        .HasForeignKey("SourceContextId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Langoose.Domain.Models.EntryContext", "TargetContext")
                        .WithMany("TargetContextTranslations")
                        .HasForeignKey("TargetContextId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourceContext");

                    b.Navigation("TargetContext");
                });

            modelBuilder.Entity("Langoose.Domain.Models.DictionaryEntry", b =>
                {
                    b.HasOne("Langoose.Domain.Models.DictionaryEntry", "BaseEntry")
                        .WithMany("DerivedForms")
                        .HasForeignKey("BaseEntryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BaseEntry");
                });

            modelBuilder.Entity("Langoose.Domain.Models.EntryContext", b =>
                {
                    b.HasOne("Langoose.Domain.Models.DictionaryEntry", "DictionaryEntry")
                        .WithMany("Contexts")
                        .HasForeignKey("DictionaryEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DictionaryEntry");
                });

            modelBuilder.Entity("Langoose.Domain.Models.EntryTranslation", b =>
                {
                    b.HasOne("Langoose.Domain.Models.DictionaryEntry", "SourceEntry")
                        .WithMany("SourceTranslations")
                        .HasForeignKey("SourceEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Langoose.Domain.Models.DictionaryEntry", "TargetEntry")
                        .WithMany("TargetTranslations")
                        .HasForeignKey("TargetEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourceEntry");

                    b.Navigation("TargetEntry");
                });

            modelBuilder.Entity("Langoose.Domain.Models.StudyEvent", b =>
                {
                    b.HasOne("Langoose.Domain.Models.DictionaryEntry", "DictionaryEntry")
                        .WithMany()
                        .HasForeignKey("DictionaryEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Langoose.Domain.Models.EntryContext", "EntryContext")
                        .WithMany()
                        .HasForeignKey("EntryContextId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DictionaryEntry");

                    b.Navigation("EntryContext");
                });

            modelBuilder.Entity("Langoose.Domain.Models.UserDictionaryEntry", b =>
                {
                    b.HasOne("Langoose.Domain.Models.DictionaryEntry", "DictionaryEntry")
                        .WithMany()
                        .HasForeignKey("DictionaryEntryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DictionaryEntry");
                });

            modelBuilder.Entity("Langoose.Domain.Models.UserProgress", b =>
                {
                    b.HasOne("Langoose.Domain.Models.DictionaryEntry", "DictionaryEntry")
                        .WithMany()
                        .HasForeignKey("DictionaryEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DictionaryEntry");
                });

            modelBuilder.Entity("Langoose.Domain.Models.DictionaryEntry", b =>
                {
                    b.Navigation("Contexts");

                    b.Navigation("DerivedForms");

                    b.Navigation("SourceTranslations");

                    b.Navigation("TargetTranslations");
                });

            modelBuilder.Entity("Langoose.Domain.Models.EntryContext", b =>
                {
                    b.Navigation("SourceContextTranslations");

                    b.Navigation("TargetContextTranslations");
                });
#pragma warning restore 612, 618
        }
    }
}
