// <auto-generated />
using System;
using System.Collections.Generic;
using Langoose.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Langoose.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Langoose.Domain.Models.BackgroundJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("ExecutionState")
                        .HasColumnType("jsonb")
                        .HasColumnName("execution_state");

                    b.Property<DateTimeOffset?>("FinishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at_utc");

                    b.Property<string>("Settings")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("settings");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_background_jobs");

                    b.ToTable("background_jobs", (string)null);
                });

            modelBuilder.Entity("Langoose.Domain.Models.ContentFlag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("DictionaryEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("dictionary_entry_id");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("boolean")
                        .HasColumnName("is_resolved");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<Guid?>("ReportedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("reported_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_content_flags");

                    b.HasIndex("DictionaryEntryId")
                        .HasDatabaseName("ix_content_flags_dictionary_entry_id");

                    b.ToTable("content_flags", (string)null);
                });

            modelBuilder.Entity("Langoose.Domain.Models.DictionaryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BaseEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("base_entry_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Difficulty")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("difficulty");

                    b.Property<string>("GrammarLabel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("grammar_label");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("language");

                    b.Property<string>("PartOfSpeech")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("part_of_speech");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("text");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_dictionary_entries");

                    b.HasIndex("BaseEntryId")
                        .HasDatabaseName("ix_dictionary_entries_base_entry_id");

                    b.HasIndex("Language", "Text", "PartOfSpeech")
                        .HasDatabaseName("ix_dictionary_entries_language_text_part_of_speech");

                    b.ToTable("dictionary_entries", (string)null);
                });

            modelBuilder.Entity("Langoose.Domain.Models.EntryContext", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cloze")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cloze");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("DictionaryEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("dictionary_entry_id");

                    b.Property<string>("Difficulty")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("difficulty");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_entry_contexts");

                    b.HasIndex("DictionaryEntryId")
                        .HasDatabaseName("ix_entry_contexts_dictionary_entry_id");

                    b.ToTable("entry_contexts", (string)null);
                });

            modelBuilder.Entity("Langoose.Domain.Models.ImportEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<float?>("AiConfidence")
                        .HasColumnType("real")
                        .HasColumnName("ai_confidence");

                    b.Property<string>("AiReasoning")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("ai_reasoning");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("language");

                    b.Property<string>("PartOfSpeech")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("part_of_speech");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<Guid?>("PromotedEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("promoted_entry_id");

                    b.Property<DateTimeOffset?>("ReviewedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at_utc");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by_user_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("source");

                    b.Property<string>("SourceRefId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("source_ref_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("StatusReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("status_reason");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("text");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_import_entries");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_import_entries_status");

                    b.HasIndex("Source", "SourceRefId")
                        .IsUnique()
                        .HasDatabaseName("ix_import_entries_source_source_ref_id");

                    b.ToTable("import_entries", (string)null);
                });

            modelBuilder.Entity("Langoose.Domain.Models.Sense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("DictionaryEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("dictionary_entry_id");

                    b.Property<string>("Gloss")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("gloss");

                    b.Property<int>("SenseIndex")
                        .HasColumnType("integer")
                        .HasColumnName("sense_index");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_senses");

                    b.HasIndex("DictionaryEntryId", "SenseIndex")
                        .IsUnique()
                        .HasDatabaseName("ix_senses_dictionary_entry_id_sense_index");

                    b.ToTable("senses", (string)null);
                });

            modelBuilder.Entity("Langoose.Domain.Models.SenseTranslation", b =>
                {
                    b.Property<Guid>("SourceSenseId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_sense_id");

                    b.Property<Guid>("TargetSenseId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_sense_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("Rank")
                        .HasColumnType("integer")
                        .HasColumnName("rank");

                    b.HasKey("SourceSenseId", "TargetSenseId")
                        .HasName("pk_sense_translations");

                    b.HasIndex("TargetSenseId")
                        .HasDatabaseName("ix_sense_translations_target_sense_id");

                    b.ToTable("sense_translations", (string)null);
                });

            modelBuilder.Entity("Langoose.Domain.Models.StudyEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("DictionaryEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("dictionary_entry_id");

                    b.Property<Guid?>("EntryContextId")
                        .HasColumnType("uuid")
                        .HasColumnName("entry_context_id");

                    b.Property<string>("FeedbackCode")
                        .HasColumnType("text")
                        .HasColumnName("feedback_code");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("UserInput")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_input");

                    b.Property<string>("Verdict")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("verdict");

                    b.HasKey("Id")
                        .HasName("pk_study_events");

                    b.HasIndex("DictionaryEntryId")
                        .HasDatabaseName("ix_study_events_dictionary_entry_id");

                    b.HasIndex("EntryContextId")
                        .HasDatabaseName("ix_study_events_entry_context_id");

                    b.HasIndex("UserId", "CreatedAtUtc")
                        .HasDatabaseName("ix_study_events_user_id_created_at_utc");

                    b.ToTable("study_events", (string)null);
                });

            modelBuilder.Entity("Langoose.Domain.Models.UserEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("EnrichmentAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("enrichment_attempts");

                    b.Property<DateTimeOffset?>("EnrichmentNotBefore")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enrichment_not_before");

                    b.Property<string>("EnrichmentStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("enrichment_status");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("PartOfSpeech")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("part_of_speech");

                    b.Property<Guid?>("SourceEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_entry_id");

                    b.Property<string>("SourceLanguage")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("source_language");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<Guid?>("TargetEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_entry_id");

                    b.Property<string>("TargetLanguage")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("target_language");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("UserInputTerm")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("user_input_term");

                    b.Property<string>("UserInputTranslation")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("user_input_translation");

                    b.HasKey("Id")
                        .HasName("pk_user_entries");

                    b.HasIndex("SourceEntryId")
                        .HasDatabaseName("ix_user_entries_source_entry_id");

                    b.HasIndex("TargetEntryId")
                        .HasDatabaseName("ix_user_entries_target_entry_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_entries_user_id");

                    b.HasIndex("EnrichmentStatus", "CreatedAtUtc")
                        .HasDatabaseName("ix_user_entries_enrichment_status_created_at_utc");

                    b.ToTable("user_entries", (string)null);
                });

            modelBuilder.Entity("Langoose.Domain.Models.UserImport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("PendingCount")
                        .HasColumnType("integer")
                        .HasColumnName("pending_count");

                    b.Property<int>("RowCount")
                        .HasColumnType("integer")
                        .HasColumnName("row_count");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_imports");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_imports_user_id");

                    b.ToTable("user_imports", (string)null);
                });

            modelBuilder.Entity("Langoose.Domain.Models.UserProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("DictionaryEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("dictionary_entry_id");

                    b.Property<double?>("Difficulty")
                        .HasColumnType("double precision")
                        .HasColumnName("difficulty");

                    b.Property<DateTimeOffset>("DueAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_at_utc");

                    b.Property<int>("FailureCount")
                        .HasColumnType("integer")
                        .HasColumnName("failure_count");

                    b.Property<DateTimeOffset?>("LastReviewedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_reviewed_at_utc");

                    b.Property<double?>("Stability")
                        .HasColumnType("double precision")
                        .HasColumnName("stability");

                    b.Property<int>("SuccessCount")
                        .HasColumnType("integer")
                        .HasColumnName("success_count");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_progress");

                    b.HasIndex("DictionaryEntryId")
                        .HasDatabaseName("ix_user_progress_dictionary_entry_id");

                    b.HasIndex("UserId", "DictionaryEntryId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_progress_user_id_dictionary_entry_id");

                    b.HasIndex("UserId", "DueAtUtc")
                        .HasDatabaseName("ix_user_progress_user_id_due_at_utc");

                    b.ToTable("user_progress", (string)null);
                });

            modelBuilder.Entity("entry_contexts_translations", b =>
                {
                    b.Property<Guid>("source_id")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<Guid>("target_id")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.HasKey("source_id", "target_id")
                        .HasName("pk_entry_contexts_translations");

                    b.HasIndex("target_id")
                        .HasDatabaseName("ix_entry_contexts_translations_target_id");

                    b.ToTable("entry_contexts_translations", (string)null);
                });

            modelBuilder.Entity("Langoose.Domain.Models.ContentFlag", b =>
                {
                    b.HasOne("Langoose.Domain.Models.DictionaryEntry", "DictionaryEntry")
                        .WithMany()
                        .HasForeignKey("DictionaryEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_content_flags_dictionary_entries_dictionary_entry_id");

                    b.Navigation("DictionaryEntry");
                });

            modelBuilder.Entity("Langoose.Domain.Models.DictionaryEntry", b =>
                {
                    b.HasOne("Langoose.Domain.Models.DictionaryEntry", "BaseEntry")
                        .WithMany("DerivedForms")
                        .HasForeignKey("BaseEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_dictionary_entries_dictionary_entries_base_entry_id");

                    b.Navigation("BaseEntry");
                });

            modelBuilder.Entity("Langoose.Domain.Models.EntryContext", b =>
                {
                    b.HasOne("Langoose.Domain.Models.DictionaryEntry", "DictionaryEntry")
                        .WithMany("Contexts")
                        .HasForeignKey("DictionaryEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_entry_contexts_dictionary_entries_dictionary_entry_id");

                    b.Navigation("DictionaryEntry");
                });

            modelBuilder.Entity("Langoose.Domain.Models.Sense", b =>
                {
                    b.HasOne("Langoose.Domain.Models.DictionaryEntry", "DictionaryEntry")
                        .WithMany("Senses")
                        .HasForeignKey("DictionaryEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_senses_dictionary_entries_dictionary_entry_id");

                    b.Navigation("DictionaryEntry");
                });

            modelBuilder.Entity("Langoose.Domain.Models.SenseTranslation", b =>
                {
                    b.HasOne("Langoose.Domain.Models.Sense", "SourceSense")
                        .WithMany("Translations")
                        .HasForeignKey("SourceSenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sense_translations_senses_source_sense_id");

                    b.HasOne("Langoose.Domain.Models.Sense", "TargetSense")
                        .WithMany()
                        .HasForeignKey("TargetSenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sense_translations_senses_target_sense_id");

                    b.Navigation("SourceSense");

                    b.Navigation("TargetSense");
                });

            modelBuilder.Entity("Langoose.Domain.Models.StudyEvent", b =>
                {
                    b.HasOne("Langoose.Domain.Models.DictionaryEntry", "DictionaryEntry")
                        .WithMany()
                        .HasForeignKey("DictionaryEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_study_events_dictionary_entries_dictionary_entry_id");

                    b.HasOne("Langoose.Domain.Models.EntryContext", "EntryContext")
                        .WithMany()
                        .HasForeignKey("EntryContextId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_study_events_entry_contexts_entry_context_id");

                    b.Navigation("DictionaryEntry");

                    b.Navigation("EntryContext");
                });

            modelBuilder.Entity("Langoose.Domain.Models.UserEntry", b =>
                {
                    b.HasOne("Langoose.Domain.Models.DictionaryEntry", "SourceEntry")
                        .WithMany()
                        .HasForeignKey("SourceEntryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_user_entries_dictionary_entries_source_entry_id");

                    b.HasOne("Langoose.Domain.Models.DictionaryEntry", "TargetEntry")
                        .WithMany()
                        .HasForeignKey("TargetEntryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_user_entries_dictionary_entries_target_entry_id");

                    b.Navigation("SourceEntry");

                    b.Navigation("TargetEntry");
                });

            modelBuilder.Entity("Langoose.Domain.Models.UserProgress", b =>
                {
                    b.HasOne("Langoose.Domain.Models.DictionaryEntry", "DictionaryEntry")
                        .WithMany()
                        .HasForeignKey("DictionaryEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_progress_dictionary_entries_dictionary_entry_id");

                    b.Navigation("DictionaryEntry");
                });

            modelBuilder.Entity("entry_contexts_translations", b =>
                {
                    b.HasOne("Langoose.Domain.Models.EntryContext", null)
                        .WithMany()
                        .HasForeignKey("source_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_entry_contexts_translations_entry_contexts_source_id");

                    b.HasOne("Langoose.Domain.Models.EntryContext", null)
                        .WithMany()
                        .HasForeignKey("target_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_entry_contexts_translations_entry_contexts_target_id");
                });

            modelBuilder.Entity("Langoose.Domain.Models.DictionaryEntry", b =>
                {
                    b.Navigation("Contexts");

                    b.Navigation("DerivedForms");

                    b.Navigation("Senses");
                });

            modelBuilder.Entity("Langoose.Domain.Models.Sense", b =>
                {
                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
